export enum PaymentMethod {
  CREDIT = 'CREDIT',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
}

export enum OrderStatus {
  RECEIVED = 'RECEIVED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
}

export enum WalletTxType {
  CREDIT_PURCHASE = 'CREDIT_PURCHASE',
  PAYMENT = 'PAYMENT',
  ADJUSTMENT = 'ADJUSTMENT',
  CREDIT_LIMIT_CHANGE = 'CREDIT_LIMIT_CHANGE',
}
